const VERIFY_OTP_START: string = 'VERIFY_OTP_START'
const VERIFY_OTP_SUCCESS: string = 'VERIFY_OTP_SUCCESS'
const VERIFY_OTP_FAIL: string = 'VERIFY_OTP_FAIL'
const AUTHENTICATE: string = 'AUTHENTICATE'
const DISMISS_ERROR: string = 'DISMISS_ERROR'
const LOGOUT: string = 'LOGOUT'

const OTP_SEND_START: string = 'OTP_SEND_START'
const OTP_SEND_SUCCESS: string = 'OTP_SEND_SUCCESS'
const OTP_SEND_FAIL: string = 'OTP_SEND_FAIL'

const VERIFY_MOBILE: string = 'VERIFY_MOBILE'
const COMPLETE_PROFILE: string = 'COMPLETE_PROFILE'

export {
  VERIFY_OTP_FAIL,
  VERIFY_OTP_START,
  VERIFY_OTP_SUCCESS,
  AUTHENTICATE,
  LOGOUT,
  OTP_SEND_FAIL,
  OTP_SEND_START,
  OTP_SEND_SUCCESS,
  DISMISS_ERROR,
  VERIFY_MOBILE,
  COMPLETE_PROFILE
}
